// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PortalOcorrenciasIPT.Data;

#nullable disable

namespace PortalOcorrenciasIPT.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260830184411_CriarImpactos")]
    partial class CriarImpactos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PortalOcorrenciasIPT.Models.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativa")
                        .HasColumnType("bit");

                    b.Property<string>("Descricao")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("Id");

                    b.ToTable("Categorias");
                });

            modelBuilder.Entity("PortalOcorrenciasIPT.Models.Impacto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<string>("Descricao")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Impactos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ativo = true,
                            Descricao = "A ocorrência tem impacto em mais do que um utilizador ou grupo.",
                            Nome = "Afeta várias pessoas"
                        },
                        new
                        {
                            Id = 2,
                            Ativo = true,
                            Descricao = "A ocorrência impede ou dificulta a realização de aulas.",
                            Nome = "Impede aulas"
                        },
                        new
                        {
                            Id = 3,
                            Ativo = true,
                            Descricao = "A ocorrência pode colocar pessoas ou bens em risco.",
                            Nome = "Risco de segurança"
                        },
                        new
                        {
                            Id = 4,
                            Ativo = true,
                            Descricao = "A ocorrência impede ou dificulta o acesso a um espaço.",
                            Nome = "Acesso bloqueado"
                        },
                        new
                        {
                            Id = 5,
                            Ativo = true,
                            Descricao = "A ocorrência já aconteceu anteriormente.",
                            Nome = "Problema recorrente"
                        },
                        new
                        {
                            Id = 6,
                            Ativo = true,
                            Descricao = "A ocorrência envolve equipamento necessário ao funcionamento normal das atividades.",
                            Nome = "Afeta equipamento essencial"
                        });
                });

            modelBuilder.Entity("PortalOcorrenciasIPT.Models.Ocorrencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Edificio")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LocalizacaoTexto")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Prioridade")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.ToTable("Ocorrencias");
                });

            modelBuilder.Entity("PortalOcorrenciasIPT.Models.OcorrenciaImpacto", b =>
                {
                    b.Property<int>("OcorrenciaId")
                        .HasColumnType("int");

                    b.Property<int>("ImpactoId")
                        .HasColumnType("int");

                    b.HasKey("OcorrenciaId", "ImpactoId");

                    b.HasIndex("ImpactoId");

                    b.ToTable("OcorrenciaImpactos");
                });

            modelBuilder.Entity("PortalOcorrenciasIPT.Models.Ocorrencia", b =>
                {
                    b.HasOne("PortalOcorrenciasIPT.Models.Categoria", "Categoria")
                        .WithMany("Ocorrencias")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("PortalOcorrenciasIPT.Models.OcorrenciaImpacto", b =>
                {
                    b.HasOne("PortalOcorrenciasIPT.Models.Impacto", "Impacto")
                        .WithMany("OcorrenciaImpactos")
                        .HasForeignKey("ImpactoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PortalOcorrenciasIPT.Models.Ocorrencia", "Ocorrencia")
                        .WithMany("OcorrenciaImpactos")
                        .HasForeignKey("OcorrenciaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Impacto");

                    b.Navigation("Ocorrencia");
                });

            modelBuilder.Entity("PortalOcorrenciasIPT.Models.Categoria", b =>
                {
                    b.Navigation("Ocorrencias");
                });

            modelBuilder.Entity("PortalOcorrenciasIPT.Models.Impacto", b =>
                {
                    b.Navigation("OcorrenciaImpactos");
                });

            modelBuilder.Entity("PortalOcorrenciasIPT.Models.Ocorrencia", b =>
                {
                    b.Navigation("OcorrenciaImpactos");
                });
#pragma warning restore 612, 618
        }
    }
}
